spring:
  application:
  name: catalog-service
woven:
  greeting: Welcome to woven book catalogs
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
