spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eswarap/config-repo
          default-label: main
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
