name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

